services:
  app:
    build: ./
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app
    stdin_open: true

  db:
    image: postgres:latest
    restart: on-failure
    volumes:
      - app:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app:


volumes:
  app:
